### ISSUE TITLE
Support for italics

### ISSUE THREAD

**Issue by lokesh-krishna** [ikornaselur/litime#33]
Would it be possible to add support for italics? And if it is, then maybe specifying which parts should be in italics? Most popular terminals in use do support italics.

**Comment by ikornaselur** [comment]
Thanks for the suggestion! I think it shouldn't be too hard to look into adding support for more styling in general, I know of some libraries that could potentially be introduced to give some support for italics, bold, underlined and fg + bg colours.

I'll have a look at it when I have some time later this week :pray:
